### ISSUE TITLE
Convert from live app to static site compiled with AWS Lambda

### ISSUE THREAD

**Issue by lpil** [redbadger/react.london#152]
``` haskell
content edit -> prismic webhook -> lambda -> compiled site -> s3
```

**Comment by asavin** [comment]
Love it!

**Comment by asavin** [comment]
It all comes down to how often the content is going to change, and how fast we want this change to reflect on the main site. We'd also need to figure out how to invalidate Cloudfront cache.

Static site will always be miles faster than something relying on a Prismic backend.

This almost sounds like something a CI could do.

**Comment by lpil** [comment]
Invalidating looks easy enough. http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/CreateInvalidation.html

I imagine there's some nice function in the AWS JS lib that makes it easier too. We could just invalidate the entire cloudfront instance on each deploy.

According to their docs it can take 10 - 15 minutes to go through. Do we think this is fast enough?

If we want to avoid this we can serve directly from the bucket or use a faster CDN. This would mean we can't use AWS certificate manager to handle the SSL though.

**Comment by asavin** [comment]
Yeah SSL is my main reason to use Cloudfront

**Comment by lpil** [comment]
Could use Cloudflare. I've found their invalidations to be mind blowingly fast.

**Comment by StuartHarris** [comment]
Hmmm, ask the Fortnum team about Cloudfare. I wouldn't go near it with a barge pole.
You can do wildcard invalidations now, with Cloudfront.

**Comment by lpil** [comment]
RE CI. If we used CI content would update only when we deploy, but we want content to update every time it is edited in prismic, so I thought lambda would fit well here.

**Comment by asavin** [comment]
What I meant is if there's CI out there smart enough to receive webhooks from anywhere (not just Github), it might as well fetch data, build and deploy the app.

**Comment by lpil** [comment]
It'd be a lot slower like that as we'd need to compile the CSS and run the tests too, no?

**Comment by dpiatek** [comment]
you alright @lpil ?

**Comment by lpil** [comment]
Yeah boss! Just been clearing out several hundred open issues :P

How have you been? Will I be seeing you at codemesh this week?

**Comment by dpiatek** [comment]
haha no problem at all @lpil . Unfortunately not this year - hope it's good.
