### ISSUE TITLE
Footer cross link always links to production

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#161]
<img width="301" alt="react_london" src="https://cloud.githubusercontent.com/assets/487468/17806331/cefaba82-65fb-11e6-8e25-6776637f7fc7.png">

When on staging, should this link also point at staging version of the conference page?

Also, should maybe the whole banner be clickable? It does look like a banner, so that would be the expected behaviour.

**Comment by lpil** [comment]
@pixelblend is working on this :)
