### ISSUE TITLE
Join Livestream link potential vulnerability

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#162]
<img width="217" alt="react_london" src="https://cloud.githubusercontent.com/assets/487468/17806544/230e90d4-65fd-11e6-962b-15938a3d32c6.png">

On the current staging "Join livestream" button is linking to `https://meetup-staging.react.london/google.com` Does this mean that the livestream URL should be specified in full on Prismic, should we clearly mention about this to the user?

**Comment by AndrewBestbier** [comment]
Checked this out and it was badly specified on prismic as google.com not http://www.google.com.

**Comment by lpil** [comment]
Should we add something to handle this user error since we can't do validation?

**Comment by Roisi** [comment]
@AndrewBestbier have we improved the documentation on this one? Was it just user error?

**Comment by AndrewBestbier** [comment]
@Roisi Was just user error. I can add a check to see if a link has http:// or I can chat to Tania or I can do both :)

**Comment by lpil** [comment]
It should already do that, thanks to the ExternalLink component, no? If we're not using it here let's fix that.

**Comment by Roisi** [comment]
We'll close this as the original bug was just user error
