### ISSUE TITLE
Sponsors logo stacking is broken on landscape Galaxy S5

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#164]
<img width="267" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/17806944/6c150aae-65ff-11e6-93aa-a8677a845788.png">

I'd expect those logos to be on the same line, like on Desktop version of a site.

**Comment by asavin** [comment]
<img width="195" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/17807058/3fa6aeea-6600-11e6-925a-b74e66dfe14a.png">

Nexus tablets seems to have exact same issue

**Comment by lpil** [comment]
Just checked, the facebook logo is not indented, it's just the image there has whitespace around it. while the RB one does not.

**Comment by asavin** [comment]
Oh no, please no whitespace around image assets

**Comment by lpil** [comment]
Images are specified by the user, it's not a dev issue.

**Comment by lpil** [comment]
But yeah I agree.
