### ISSUE TITLE
Layout issues on Kindle Fire HD 7 and 8.9, Android 4 and 4.3

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#165]
Multiple issues with the site on Kindle Fire HD tablets

<img width="220" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/17807226/281e160e-6601-11e6-913b-2ad51ccc610b.png">

<img width="211" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/17807269/58b5d662-6601-11e6-826d-1a0c1933a973.png">

<img width="206" alt="dashboard" src="https://cloud.githubusercontent.com/assets/487468/17807280/69496b56-6601-11e6-9dcb-974733b81666.png">

**Comment by lpil** [comment]
Is that accurate? It's completely failing to do basic SVG rendering which caniuse says it should be able to do.

**Comment by asavin** [comment]
Browserstack seems to only have simulations, so might not be 100% accurate

**Comment by Roisi** [comment]
We should retest this as it was before autoprefixer

**Comment by Roisi** [comment]
this is ok now, marking as fixed
