### ISSUE TITLE
Weird baby G on add to calender - IE11

### ISSUE THREAD

**Issue by Roisi** [redbadger/react.london#174]
the G on IE11 "add to calendar" button is a baby like the mailing list box
<img width="232" alt="screen shot 2016-08-26 at 10 15 03" src="https://cloud.githubusercontent.com/assets/8049847/18000485/4588b88c-6b76-11e6-87cc-45f82a67af79.png">

**Comment by asavin** [comment]
This is duplicate of https://github.com/redbadger/react.london/issues/163
