### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by JoeStanton** [redbadger/react.london#20]
Ladybadgers and I think it'd be a good idea to implement and link to a code of conduct for the React London conference. This should hopefully help with attendee diversity and all of those other nice things we all agree with 💃

**Comment by lpil** [comment]
@JoeStanton Do we have one already?

**Comment by JoeStanton** [comment]
Don't think so!

**Comment by lpil** [comment]
This has been moved to Trello.
