### ISSUE TITLE
GetUpdates - Update the error message on the format of email to be more user friendly

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#207]
Error messages can be more userfriendly if 'Get Updates' is clicked without entering a correct formatted email or no email at all.

### to repro:

1. Go to https://staging.react.london/
2. Enter an email with some wrong format (or leave it empty) and hit 'Get Updates'

<img width="609" alt="screen shot 2016-09-01 at 10 56 34" src="https://cloud.githubusercontent.com/assets/16544365/18163427/e3da50de-7032-11e6-9f44-ea66ed8e6f84.png">

**Comment by leilafi** [comment]
Other case is when re-submitting an existing email.

### to repro
1. Enter an existing email
2. Hit Get Updates

<img width="613" alt="screen shot 2016-09-01 at 11 18 11" src="https://cloud.githubusercontent.com/assets/16544365/18164049/ddac26d0-7035-11e6-9cee-2f4fba67dd60.png">

**Comment by Roisi** [comment]
as this is more an issue within mailchimp going to close for now, we can revisit when we're doig the RB mailing list stuff
