### ISSUE TITLE
GetUpdates - Preffered format of only appears when there is an error in the submitted email

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#208]
Preffered format of received emails only appears when there is an error on the submitted email. It should be either displayed when an email with the correct format is submitted or not at all.

#### to repro
1. Go to https://staging.react.london/
2. Leave email field empty
3. Hit 'Get Updates'

<img width="170" alt="screen shot 2016-09-01 at 10 59 04" src="https://cloud.githubusercontent.com/assets/16544365/18163581/9b02f7c0-7033-11e6-82fd-ac901544f916.png">

**Comment by zoeabryant** [comment]
We can turn this off in the settings:
-Go to Lists –> List name and defaults –> uncheck the option: “let your subscribers pick an email format?”
if preferred

**Comment by zoeabryant** [comment]
Amy has stated that she'd rather let users have this option for accessibility reasons.
Next step is to see in mailchimp if there's any way we can put all users through this choice.

**Comment by zoeabryant** [comment]
> In addition to your HTML, you should send a plain-text alternative version of your message for those people who can't view HTML emails. When a recipient receives your email, their email program will automatically determine which format to display. 
http://kb.mailchimp.com/campaigns/ways-to-build/about-html-email

basically:

* users who are using a mail browser that don't support HTML email will get a plain text email by default, regardless of their preferred format.
* users who have set their preference obviously get their preferred format
* users can set their preference when signing up in the above situation, or by clicking on the  `Update your preferences` link in the footer of every email.

I don't think there's any action to take here - unless we want to make it clearer that people can set their preference?

**Comment by Roisi** [comment]
Closing this, I think we're good
