### ISSUE TITLE
GetUpdates - RedBadger/React logos are not hyperlinks in subscription page

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#209]
Perhaps RedBadger and React logos should be hyperlinks?

#### to repro
1. Go to https://staging.react.london/
2. Enter some email and hit 'Get Updates'
3. On the subscription page hover over the logos and notice that they are not links

<img width="605" alt="screen shot 2016-09-01 at 11 06 51" src="https://cloud.githubusercontent.com/assets/16544365/18163705/365487ac-7034-11e6-859d-46f412e0b546.png">

**Comment by lpil** [comment]
It's a single image, so it's only possible to link to one place... Seems this design is misleading.

I'm not sure if mailchimp will let us make the image a link. @AndrewBestbier Do you know how to set this up?

**Comment by Roisi** [comment]
as this is more an issue within mailchimp going to close for now, we can revisit when we're doig the RB mailing list stuff

**Comment by AndrewBestbier** [comment]
Don't think we can change this. We can't really control MailChimp that much
