### ISSUE TITLE
GetUpdates - Confirmation form of sent email to updat perfrences needs styling

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#212]
Confirmation form of sent email to updat perfrences needs styling.
<img width="627" alt="screen shot 2016-09-01 at 11 08 38" src="https://cloud.githubusercontent.com/assets/16544365/18163872/fe11faae-7034-11e6-8343-10b8a31e4d33.png">

#### to repro
1. Go to https://staging.react.london/
2. Enter an email which already been submitted
3. Hit 'Get Updates'
4. Click on 'Click here to update your profile.'

**Comment by Roisi** [comment]
as this is more an issue within mailchimp going to close for now, we can revisit when we're doig the RB mailing list stuff
