### ISSUE TITLE
Menu - Menu does not always load

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#213]
For menu (About/ Partners/...) doesn't always load on the page.

#### to repro
1. Go to https://staging.react.london/
2. Refresh

<img width="973" alt="screen shot 2016-09-01 at 11 42 11" src="https://cloud.githubusercontent.com/assets/16544365/18164691/2aeacbe2-7039-11e6-9484-95b76f573513.png">

**Comment by lpil** [comment]
The navbar has just been removed. You must have been checking out the site during a deploy :)
