### ISSUE TITLE
Menu - Clicking 'TICKETS' shifts the menu items to left

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#214]
Clicking 'TICKETS' shifts the menu items to left. Might be difficult to repro because the menu does not load everytime.

#### to repro
1. Go to https://staging.react.london/
2. Click on 'TICKETS'

**Comment by lpil** [comment]
The navbar has been removed until the content is ready, so hard to investigate

**Comment by zoeabryant** [comment]
blocked - we should double check this when the navbar is put back in place

**Comment by Roisi** [comment]
Checked this now the nav is back in and cannot reproduce (probably as we've made quite a few design tweaks since)
