### ISSUE TITLE
GetUpdates - Just to confirm the responsive desgin

### ISSUE THREAD

**Issue by leilafi** [redbadger/react.london#215]
Should it look like this?

<img width="377" alt="screen shot 2016-09-01 at 11 52 36" src="https://cloud.githubusercontent.com/assets/16544365/18165025/e8aa67e0-703a-11e6-93c0-9f5aa86370ef.png">

**Comment by zoeabryant** [comment]
I have confirmed with Sari that this is intentional and ok :)
