### ISSUE TITLE
Speakers page - iphone 5 - doesn't resize correctly

### ISSUE THREAD

**Issue by Roisi** [redbadger/react.london#241]
there are some layout issues on the speakers page on iphone 5 as shown in the below screenshot
<img width="398" alt="screen shot 2016-09-14 at 13 56 20" src="https://cloud.githubusercontent.com/assets/8049847/18513033/a0733634-7a83-11e6-9115-1f1e92aab888.png">

**Comment by samsmith1983** [comment]
I can not repro this with an iPhone 5S on iOS9. iOS8 looks screwed though - but then everything looks screwed on iOS8. 

@Roisi I'm closing this for now - please reopen if you can still get it to happen 😃
