### ISSUE TITLE
Use ExternalLink everywhere instead of a

### ISSUE THREAD

**Issue by lpil** [redbadger/react.london#247]

**Comment by Roisi** [comment]
@asavin what is this? is it relevant?

**Comment by Roisi** [comment]
actually, we're going to close this because there's no associated information

**Comment by lpil** [comment]
It's a code quality thing. ExternalLink is a react component that is supposed to be used in place of an `a` tag for security reasons when it's a link to an external site. It's missing in a few places.

**Comment by lpil** [comment]
+ hi! :wave:
