### ISSUE TITLE
tickets page - padding on ticket types

### ISSUE THREAD

**Issue by Roisi** [redbadger/react.london#255]
there is not enough padding on the ticket types on iPhone which means they brush the edge of the screen
![needs_more_left_padding_on_mobile______720](https://cloud.githubusercontent.com/assets/8049847/18837084/63b72a0e-83fa-11e6-87d3-f0bcb1de9d93.jpg)

**Comment by samsmith1983** [comment]
This looks fixed:

![screen shot 2017-01-13 at 11 23 23](https://cloud.githubusercontent.com/assets/22592849/21928441/c32ffe1a-d982-11e6-9759-63175437dd86.png)
