### ISSUE TITLE
''Become a Partner'' button doesn't work on windows op system

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/react.london#261]
''Become a Partner'' button doesn't work on windows operating systems. It redirects the user to an empty page instead of opening the email.

**Comment by Roisi** [comment]
@samsmith1983

**Comment by samsmith1983** [comment]
This works fine for me; the link is a standard `mailto:` type. I imagine this was a Windows setup issue - perhaps no mail client assigned?
