### ISSUE TITLE
Send mail icon in the footer doesn't work on windows

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/react.london#262]
Send mail icon in the footer doesn't work on windows. The link is there but id doesn't open any mail app. Happens only on windows operating systems.

**Comment by Roisi** [comment]
@samsmith1983 to verify

**Comment by samsmith1983** [comment]
This works fine for me; the link is a standard mailto: type. I imagine this was a Windows setup issue - perhaps no default mail client assigned?
