### ISSUE TITLE
Phone number clickable on Edge

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/react.london#263]
The phone number from ''plan you visit'' paragraph is clickable on Edge browser. It shouldn't be because this is a feature only for mobile phones.

**Comment by samsmith1983** [comment]
I can't repro this, but then the number seems to not be clickable at all (even on mobile) now. I've logged #292. 

However, I'm not sure this is really a bug as it should just be a `tel:` link?

**Comment by Roisi** [comment]
@samsmith1983 to confirm whether or not he is talking out of his arse

**Comment by samsmith1983** [comment]
I was basically talking out of my arse. Phone number is not clickable on any desktop browser, but is clickable on mobile.

Going to close this.
