### ISSUE TITLE
Add to Calendar link creates wrong event

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#280]
<img width="351" alt="react_london" src="https://cloud.githubusercontent.com/assets/487468/21647079/c7d62e74-d290-11e6-80ab-78af933bdbeb.png">

<img width="662" alt="red_badger_-_calendar_-_event_details" src="https://cloud.githubusercontent.com/assets/487468/21647061/b6375b70-d290-11e6-9f3a-bd34462ace4b.png">

**Comment by samsmith1983** [comment]
This was fixed in #283
