### ISSUE TITLE
"Become a speaker" button should be at the top paragraph

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/react.london#281]
"Become a speaker" button should be at the top paragraph, per the design:
https://app.zeplin.io/project.html#pid=57bac5a5323e4f1d1167b761&sid=585027d28f324e927b86ee73

How it is currently:
![screen shot 2017-01-04 at 15 19 57](https://cloud.githubusercontent.com/assets/22592849/21647234/54d0f0de-d291-11e6-9319-88ca59276627.png)

How it should be:
![screen shot 2017-01-04 at 15 20 14](https://cloud.githubusercontent.com/assets/22592849/21647244/5d548ec8-d291-11e6-98a3-59574b6f20ff.png)

**Comment by lazydevorg** [comment]
@samsmith1983 should we close it?

**Comment by samsmith1983** [comment]
Yeah let's just wait until it's live then close it :)

**Comment by samsmith1983** [comment]
This has now been deployed. Closing.
