### ISSUE TITLE
Partners page: Ticketmaster logo is too wide for page, causing ugliness on mobile

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/react.london#285]
Tested on an iPhone 6S using iOS 9

Repro:

- Grab an iPhone 
- Go to react.london/partners
- Scroll down a bit

You'll see this:

![screen shot 2017-01-09 at 09 59 41](https://cloud.githubusercontent.com/assets/22592849/21762835/bd68c206-d652-11e6-9f0c-8861671bfe56.png)

**Comment by samsmith1983** [comment]
@Roisi

**Comment by Roisi** [comment]
this is ok now
