### ISSUE TITLE
Jobs Page: odd empty bar shows under the header

### ISSUE THREAD

**Issue by Monikamu** [redbadger/react.london#311]
**Description of the issue:**

When there are no gold tier jobs there is still an empty box displaying. 

**Browser used:**
Any
**OS used:**
Any
**Device used:**
Any

**Steps to reproduce:**

1. go here: https://react.london/jobs

**Actual result:**
<img width="1111" alt="screen shot 2017-01-30 at 16 22 55" src="https://cloud.githubusercontent.com/assets/16961478/22431434/63326b6c-e709-11e6-9ae0-a9469e7c57ec.png">

**Expected result:**
Remove the light blue section above the job post.

**Comment by chris-brookes** [comment]
After speaking to @asavin I am going to close this issue. This issue is only appearing due to no jobs advertised in this specific section. At the moment and into the future there will be content, so the issue will not appear.
