### ISSUE TITLE
Design tweaks to inclusivity blog article

### ISSUE THREAD

**Issue by anurbanromantic** [redbadger/react.london#313]
**Description of the issue:**
Design tweaks to inclusivity blog article

**Browser used:**
Any
**OS used:**
Any
**Device used:**
Any

**Steps to reproduce:**

1. Go to https://react.london/speakers
2. Scroll to inclusivity blog article section

**Actual result:**
<img width="786" alt="screen shot 2017-01-31 at 10 20 34" src="https://cloud.githubusercontent.com/assets/11541119/22460886/f058ddce-e79e-11e6-8184-d036d9882642.png">

**Expected result:**

- [x] Make quote marks curly (instead of "." do “.”)
- [x] Make GET ME A TICKET button text bold

**Comment by chris-brookes** [comment]
Re-tested. The button text is now bold, but the quote marks have not been changed.
