### ISSUE TITLE
Partners page layout is broken with too long landscape logos

### ISSUE THREAD

**Issue by asavin** [redbadger/react.london#314]
**Description of the issue:**

<img width="580" alt="react_london" src="https://cloud.githubusercontent.com/assets/487468/22471675/f68a2708-e7ca-11e6-81d6-d23965a24390.png">

**Browser used:**
**OS used:**
**Device used:**

**Steps to reproduce:**

1. Assign a very long landscape logo to a conference partner
2. Check the partners page

**Actual result:**

Refer to the screenshot

**Expected result:**

Layout not broken

**Comment by asavin** [comment]
Seems like we're going to control layout of the logo assets and solve this issue that way.

**Comment by Roisi** [comment]
Closing this as we're fixing through asset management
