### ISSUE TITLE
CFP copy out of date

### ISSUE THREAD

**Issue by stevecottle** [redbadger/react.london#318]
**Description of the issue:**
![react_london_and_slack_-_red_badger](https://cloud.githubusercontent.com/assets/11883999/22554456/013b0f26-e958-11e6-9c47-ac6cdf4ca33b.jpg)
^Copy out of date

**Browser used:**
All

**OS used:**
All

**Device used:**
All

**Steps to reproduce:**

1. Go to https://react.london/schedule
2. 
3.
...etc

**Actual result:**
Copy is out of date

**Expected result:**
Copy should read:

Lightning talks close 5 Feb

**Comment by asavin** [comment]
CFP is disabled now
