### ISSUE TITLE
Time on Schedule page needs "am" added to it

### ISSUE THREAD

**Issue by gregdorward** [redbadger/react.london#332]
**Description of the issue:**
On the Schedule page, we display the time of the conference as 8:30 - 9pm - This reads as though it only goes for half an hour in the evening. We should change it to be 8:30am - 9pm

**Browser used:**
Any

**OS used:**
Any

**Device used:**
Any

**Steps to reproduce:**

1. Navigate to the Schedule page
2. Check the times at the top of the page

**Actual result:**
"8:30 - 9pm" is shown

<img width="559" alt="screen shot 2017-02-16 at 10 29 36" src="https://cloud.githubusercontent.com/assets/20296527/23017722/5971c12c-f433-11e6-809c-f3341a329a0f.png">

**Expected result:**
"8:30am - 9pm" should be shown

**Comment by stevecottle** [comment]
Agreed
