### ISSUE TITLE
Meetup site: Link [QEII Center, London SW1P 3EE] goes to Ghana

### ISSUE THREAD

**Issue by stevecottle** [redbadger/react.london#337]
**Description of the issue:**
Conference address links to somewhere off the coast of Ghana

**Browser used:**
Chrome

**OS used:**
OSX El Capitan

**Device used:**
MacbookPro

**Steps to reproduce:**

1. Go to https://meetup.react.london/ 
2. Scroll down to blue React London box
3. Click on QEII Center, London SW1P 3EE
4. maps.google opens up to coordinates 0°00'00.0"N 0°42'11.3"W

**Actual result:**
maps opens to wrong location

**Expected result:**
maps to open to QEII Center, London SW1P 3EE

**Comment by romanschejbal** [comment]
So this was a data problem. I've updated the coordinates and published.
