### ISSUE TITLE
React London - job descriptions not displaying

### ISSUE THREAD

**Issue by Roisi** [redbadger/react.london#338]
**Description of the issue:**
As per design for the jobs page, the job description of each job should show on the jobs page, but at the moment it does not come through
**Browser used:**
all
**OS used:**
all
**Device used:**
all

**Steps to reproduce:**

1. Go to the jobs section in prismic
2.note that the "job description" section has content
3. Go to the jobs page on react.london
4. note abscence of content
...etc

**Actual result:**
Job description does not appear
**Expected result:**
Job description should appear

**Comment by asavin** [comment]
This one is working as designed - only gold level partners will get job descriptions displayed, but not silver or bronze levels.

Fixing this will require design change.

**Comment by Roisi** [comment]
this is working as expected. closing
