### ISSUE TITLE
React London advert update

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/react.london#354]
**Description of the issue:**
Update the text on the React London 2017 advert at the bottom of the meetup.react.london home page. (mobile, tablet and desktop version)

Change the text from "We’re launching a new conference focused on React." to "We hosted the 1st React.js conference in London in March 2017"

<img width="1082" alt="screen shot 2017-04-07 at 13 24 06" src="https://cloud.githubusercontent.com/assets/9529865/24799881/8cd0defc-1b95-11e7-9eda-3d44f20200e0.png">

**Comment by grahammendick** [comment]
I checked with Amy and we agreed to 
* replace 1st with first
* drop the .js after the word React

The text should read "We hosted the first React conference in London in March 2017"

**Comment by grahammendick** [comment]
I've also retained the full stop fro the original text

**Comment by gregdorward** [comment]
Looks good to me - happy to merge this one once it's had a review
