### ISSUE TITLE
YouTube videos no longer linked correctly

### ISSUE THREAD

**Issue by gregdorward** [redbadger/react.london#356]
**Description of the issue:**
The links to the React London YouTube videos are no longer working. It looks like the videos may have been modified in the last week or so, but we never updated the url

**Browser used:**
All

**OS used:**
All

**Device used:**
All

**Steps to reproduce:**

1. On the React London site, click on any of the 3 YouTube videos

**Actual result:**
'This video has been removed by the user.' message is shown in YouTube

**Expected result:**
The videos should be linked correctly

Additional information: 

The playlist looks to be unaffected by this

**Comment by chris-brookes** [comment]
@dstodolny 
Christopher Chedeau - https://www.youtube.com/watch?v=0Q4kUNx85_4
Andrey Sitnik - https://www.youtube.com/watch?v=3LecnX1hjyw
Cheng Lou - https://www.youtube.com/watch?v=24S5u_4gx7w
