### ISSUE TITLE
SSL cert

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/react.london#37]
As raised by @kadikraman  "Can we pop an SSL cert onto the react.london site? Would help with SEO and general trustworthiness :smile: "

**Comment by lpil** [comment]
Requested a cert with the AWS Cert Manager

**Comment by zoeabryant** [comment]
@lpil any update on this?

**Comment by lpil** [comment]
Nope. We need to stick cloudfront in front of S3 to achieve this, and if we do that we need to start thinking about cache busting

**Comment by lpil** [comment]
Moved to the board
