### ISSUE TITLE
Handling missing data

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/react.london#6]
If data is missing, particularly in the Preview component, right now there are a bunch of ugly if statements to avoid an error being thrown. We need a better, more thorough way doing this.

**Comment by chris-goodchild** [comment]
A quick out-of-the box solution might be to use Lodash (you can take a dependency on individual methods or method categories such as array, collection, etc). Its array methods handle undefined input which negates the need for any up-front type checks.

Alternatively, we could create our own predicate combinators to ensure code paths run only when the input is defined and/or matches a specific type.

**Comment by lpil** [comment]
Fixed by #22

**Comment by zoeabryant** [comment]
Editor.js:25 Uncaught TypeError: Cannot read property 'map' of undefined
@lpil

**Comment by lpil** [comment]
Mysterious machine specific bug :(

**Comment by zoeabryant** [comment]
Addressed in #28

**Comment by lpil** [comment]
It was a breaking change in redux form.
