### ISSUE TITLE
Editor MVP

### ISSUE THREAD

**Issue by lpil** [redbadger/react.london#60]
- [x] Server can serve existing site content data
- [x] Server can persist existing site content data
- [x] Editor can load existing site content
  - [x] Saga
  - [x] Tests
- [x] Editor can be used to edit content
- [ ] head copied across
- [x] Homepage component
- [x] Community component
- [x] Conference component
- [x] In editor preview
- [ ] Publishing to live site
  - [x] Saga implementation #63 
  - [x] Saga hooked up to view layer
  - [x] Tests
  - [ ] Event and community state can be edited with form
    - [x] Event form populated with initial state
    - [x] Community form populated with initial state
    - [x] Form changes sync to state tree (events) #66 
    - [x] Form changes sync to state tree (community)
    - [ ] Can select an event to use for the community page
    - [x] Existing events can be selected for editing
    - [x] New events can be created
  - [x] Publish button
  - [x] Site endpoint saves data for later loading
  - [x] Site endpoint compiles CSS
  - [ ] Site endpoint copies images etc across
  - [ ] Site endpoint compiles homepage
  - [ ] Site endpoint compiles conference page
  - [ ] Site endpoint compiles community page
  - [ ] Site endpoint pushes all compiled files to S3

**Comment by zoeabryant** [comment]
- Editor can load existing site content
     --- eg client side makes GET to /site, gets JSON, puts in redux shizzle.
-  Editor can push content to site endpoint
    --- take redux state shizxle, PUT to /site (which then does it's thing with heroku)

**Comment by zoeabryant** [comment]
**Future**
- [ ] Draft/Published functionality

**Comment by zoeabryant** [comment]
Don't forget #44 is relevent to this

**Comment by zoeabryant** [comment]
And #50 


- [ ] Error handling for:
   - [ ] 403 authentication
   - [ ] 404 not live/staging
   - [ ] 500 screwed
   - [ ] 413 (Payload Too Large)
   - [ ] No content to deploy

^ these need to be reflected on the front end so the user can react accordingly.
(if still relevant)

**Comment by lpil** [comment]
PIVOT!
