### ISSUE TITLE
Meetup page_Safari

### ISSUE THREAD

**Issue by TaniaPasia** [redbadger/react.london#68]
<img width="1280" alt="screen shot 2016-06-27 at 17 51 50" src="https://cloud.githubusercontent.com/assets/11243855/16388168/ba6a0dce-3c8f-11e6-954c-452ca06cf904.png">

Logo is not centred.

Repro:
Go to http://staging.react.london/#

**Comment by zoeabryant** [comment]
fixed in https://github.com/redbadger/react.london/commit/337ceb0f6cf6370e9de0786d15d94874a34c7b3a
(not yet live)
