### ISSUE TITLE
Meetup page_footer on Firefox 

### ISSUE THREAD

**Issue by TaniaPasia** [redbadger/react.london#69]
<img width="1280" alt="screen shot 2016-06-27 at 17 57 00" src="https://cloud.githubusercontent.com/assets/11243855/16388321/82dc65e0-3c90-11e6-99a5-8eeb5f0eb9b4.png">

Social media icons are in one column

Repro:
Go to http://staging.react.london/#

**Comment by zoeabryant** [comment]
Fixed in https://github.com/redbadger/react.london/commit/854e60496b78512334f934de3cb7c39cfc66ccfe
(not live yet)
