### ISSUE TITLE
Firefox_Sign up form

### ISSUE THREAD

**Issue by TaniaPasia** [redbadger/react.london#70]
<img width="1280" alt="screen shot 2016-06-28 at 12 22 38" src="https://cloud.githubusercontent.com/assets/11243855/16413638/f4584988-3d2a-11e6-85fd-f5ce0cc566ba.png">

<img width="1280" alt="screen shot 2016-06-28 at 12 26 33" src="https://cloud.githubusercontent.com/assets/11243855/16413705/7e325356-3d2b-11e6-8ada-8af2e24cd624.png">

Sign up form is looking funny and not centred aligned

**Comment by zoeabryant** [comment]
@TaniaPasia would you mind checking this again? Might have been fixed as part of https://github.com/redbadger/react.london/commit/966c3279a3d65a377836054b80a233051f0305aa

**Comment by zoeabryant** [comment]
confirmed fixed
