### ISSUE TITLE
Chrome - Desktop

### ISSUE THREAD

**Issue by TaniaPasia** [redbadger/react.london#73]
Little badger is not showing properly
<img width="401" alt="screen shot 2016-06-28 at 14 25 13" src="https://cloud.githubusercontent.com/assets/11243855/16416920/19eb2948-3d3c-11e6-99ea-079ec79e5319.png">

**Comment by zoeabryant** [comment]
addressed in https://github.com/redbadger/react.london/commit/8db2d131408929a643261c62d1d5cabe780680bd
