### ISSUE TITLE
Conf submit button sometimes square

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/react.london#9]
styling is off - cross browser requirments

**Comment by MarcelCutts** [comment]
Not sure what triggers it, it's not consistent, but it looks like so when it goes wrong.
<img width="691" alt="screen shot 2016-06-02 at 11 09 21" src="https://cloud.githubusercontent.com/assets/5721314/15741657/895f0d88-28b2-11e6-8ad2-e55d934126f4.png">

**Comment by MarcelCutts** [comment]
OK - this one is figured out. 🎉 

Adblockers and some corporate Wifis block things from certain mailchimp URIs, including the mailchimp CSS it tries to pull down!

Solution - apply our own styles on this one.

**Comment by zoeabryant** [comment]
Sorted
